### PR TITLE
[#160474171] get all orders

### PR DESCRIPTION
**Pull request by ongebo**
I made changes to define flask routes for fetching all orders. I created two orders endpoints, one for the customer, another for the admin. Please help me to review the code, and advise me as to whether I should have only one endpoint or whether two endpoints are okay

### CODE REVIEW

**Comment by katunold** [comment]
The builds are passing, I think your doing a great job

**Comment by SokoPaulSokool** [comment]
I thought the question asked us to create APIs for the customer's side only since it's only the customer that can place orders.

**Comment by KicaRonaldOkello** [comment]
Please return status codes for every action

**Comment by ongebo** [comment]
@SokoPaulSokool, how about updating the status of an order (Accept, Decline, or Mark as complete), those are admin actions so I think that we are creating for both admin and customers, what do you say?

**Pull request merged**
